### PR TITLE
Be more helpful to people who don't know usage

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by azur1s** [comment]
Hey, can you pull the lastest commit and try this again? I can't edit your fork sorry

**Comment by azur1s** [comment]
i'm closing this because its only 2 lines of code, but thanks tho :D

**Comment by ghost** [comment]
That's not how you deal with PRs. You should leave it open, waiting for the requester to fix.
Please don't absent-mindedly close a PR next time, ***please***.

**Comment by azur1s** [comment]
sorry, this is my first big project and i dont know how to manage a project correctly, im sorry

**Comment by ghost** [comment]
I know, you look very new to the opensource community.
I'm pretty new to it too, so I'll just say a few things that are fundamental.
1. Respect other contributors
2. Never close an issue or a PR without permission or certainty
Anyways, I wish you good luck on OSS dev!

**Comment by azur1s** [comment]
thanks a lot, ill try my best on github :D

**Pull request closed without merging**
